--######
USE ROLE ACCOUNTADMIN;
-- Enable logs, metrics and traces
ALTER DATABASE ML_DB SET LOG_LEVEL = INFO;
ALTER DATABASE ML_DB SET METRIC_LEVEL = ALL;
ALTER DATABASE ML_DB SET TRACE_LEVEL = ALWAYS;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS AI_WH WITH WAREHOUSE_SIZE='SMALL';
USE WAREHOUSE AI_WH;

-- Create Notebook
CREATE OR REPLACE NOTEBOOK ML_DB.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK 
    FROM '@ML_DB.PUBLIC.GITHUB_REPOSITORY_SNOWFLAKE_SIMPLE_MLOPS/branches/main/src/' 
    QUERY_WAREHOUSE=AI_WH
    MAIN_FILE='MLOPS_DEMO.ipynb'
    COMPUTE_POOL=SYSTEM_COMPUTE_POOL_CPU
    RUNTIME_NAME=SYSTEM$BASIC_RUNTIME

ALTER NOTEBOOK ML_DB.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK  ADD LIVE VERSION FROM LAST;

-- Provide link to notebook
SELECT 'Visit the demo notebook here: ' AS DEMO_INSTRUCTIONS
UNION ALL
SELECT CONCAT_WS('/', 'https://app.snowflake.com',CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME(), '#/notebooks/ML_DB.PUBLIC.SIMPLE_MLOPS_DEMO_NOTEBOOK') AS DEMO_INSTRUCTIONS;